server:
  port: 5503
  host: localhost
auth:
  jwksUri: http://localhost:7373/.well-known/jwks.json
database:
  url: mongodb+srv://order:order@cluster.wkcu5.mongodb.net/order?retryWrites=true&w=majority&appName=Cluster
kafka:
  broker: 
    - localhost:9092
  sasl:
    username: ''
    password: ''
razorpay:
  keyId: rzp_test_AsM8JZVbJPRkdy
  secretKey: tztgtHbuzdD6DnXOZpG9IZUl
  webhookSecret: adarshnaik@2004

catlog:
  url: http://localhost:8000/api/catalog

frontend:
  clientUI: http://localhost:3000
  adminUI: http://localhost:5173
